version: "3.7"

services:
  payd:
    container_name: payd
    image: local.payd
    environment:
      DB_DSN: "file:paydb/wallet.db?cache=shared&_foreign_keys=true"
      DB_SCHEMA_PATH: "migrations"
      LOG_LEVEL: "info"
      DPP_HOST: "ws://dpp:8445/ws"
      MAPI_CALLBACK_HOST: "http://dpp:8445"
      PEERCHANNELS_HOST: "peerchannels:25009"
      WALLET_SPVREQUIRED: 'true'
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:8443/api/v1/health" ]
      interval: 30s
      timeout: 10s
    volumes:
      - payd-data:/paydb
    ports:
      - "8443:8443"
    networks:
      - regtest-stack

  payd-merchant:
    container_name: payd-merchant
    image: local.payd:latest
    environment:
      DB_DSN: "file:paydb/merchant-wallet.db?cache=shared&_foreign_keys=true"
      DB_SCHEMA_PATH: "migrations"
      SERVER_HOST: payd-merchant:28443
      SERVER_PORT: :28443
      LOG_LEVEL: "info"
      DPP_HOST: "ws://dpp-merchant:28445/ws"
      MAPI_CALLBACK_HOST: "http://dpp-merchant:28445"
      PEERCHANNELS_HOST: "peerchannels:25009"
      WALLET_SPVREQUIRED: 'true'
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:28443/api/v1/health" ]
      interval: 30s
      timeout: 10s
    volumes:
      - merchant-data:/paydb
    ports:
      - "28443:28443"
    networks:
      - regtest-stack

networks:
  regtest-stack:
    name: regtest-stack
    external: true

volumes:
  payd-data:
    external: false
  merchant-data:
    external: false
