version: '3.8'

services:
  node1:
    container_name: node1
    image: bitcoinsv/bitcoin-sv:1.0.8
    expose:
      - "18332"
      - "18333"
      - "28332"
    ports:
      - "18332:18332"
      - "28332:28332"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./regtest/sv/bitcoin.conf:/data/bitcoin.conf
      - regtest-data:/data

  minerid:
    container_name: minerid
    image: bitcoinsv/minerid:1.1.1
    environment:
      NODE_CONFIG: '{
        "bitcoin": {
        "rpcHost":"node1"
        },
        "network": "regtest"
        }'
    ports:
      - "9012:9002"
    restart: unless-stopped
    depends_on:
      - node1
    volumes:
      - minerid:/root/.keystore
      - minerid:/root/.minerid-client
    command: ["/bin/sh", "-c", "npm run cli -- generateminerid --name testMiner; npm start;"]

  mapi_db:
    container_name: mapi_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - mapi-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mapi:
    container_name: mapi
    image: bitcoinsv/mapi:1.3.0
    environment:
      - ConnectionStrings__DBConnectionString=Server=mapi_db;Port=5432;User Id=merchant;Password=merchant;Database=merchant_gateway;
      - ConnectionStrings__DBConnectionStringDDL=Server=mapi_db;Port=5432;User Id=merchantddl;Password=merchant;Database=merchant_gateway;
      - ConnectionStrings__DBConnectionStringMaster=Server=mapi_db;Port=5432;User Id=postgres;Password=postgres;Database=merchant_gateway;
      - AppSettings__QuoteExpiryMinutes=10
      - AppSettings__ZmqConnectionTestIntervalSec=60
      - AppSettings__RestAdminAPIKey=apikey
      - AppSettings__DeltaBlockHeightForDoubleSpendCheck=144
      - AppSettings__CleanUpTxAfterDays=3
      - AppSettings__CleanUpTxPeriodSec=3600
      - AppSettings__CheckFeeDisabled=false
      - AppSettings__WifPrivateKey=
      - AppSettings__DSHostBanTimeSec=300
      - AppSettings__DSMaxNumOfTxQueries=5
      - AppSettings__DSCachedTxRequestsCooldownPeriodSec=300
      - AppSettings__DSMaxNumOfUnknownTxQueries=100
      - AppSettings__DSUnknownTxQueryCooldownPeriodSec=300
      - AppSettings__DSScriptValidationTimeoutSec=5
      - AppSettings__EnableHTTP=true
      - AppSettings__Notification__NotificationIntervalSec=60
      - AppSettings__Notification__InstantNotificationsTasks=2
      - AppSettings__Notification__InstantNotificationsQueueSize=1000
      - AppSettings__Notification__MaxNotificationsInBatch=100
      - AppSettings__Notification__SlowHostThresholdInMs=1000
      - AppSettings__Notification__InstantNotificationsSlowTaskPercentage=20
      - AppSettings__Notification__NoOfSavedExecutionTimes=10
      - AppSettings__Notification__NotificationsRetryCount=10
      - AppSettings__Notification__SlowHostResponseTimeoutMS=1000
      - AppSettings__Notification__FastHostResponseTimeoutMS=2000
      - AppSettings__MinerIdServer__Url=http://minerid:9002/minerid
      - AppSettings__MinerIdServer__Alias=testMiner
      - AppSettings__MinerIdServer__Authentication=
      - ASPNETCORE_ENVIRONMENT=PRODUCTION
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=9014
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/config/localhost.pfx
    ports:
      - "9014:80"
    restart: unless-stopped
    volumes:
      - ./regtest/mapi/config:/config/:ro
    depends_on:
      - node1
      - minerid
      - mapi_db

  mapi_add_node:
    container_name: mapi_add_node
    image: curlimages/curl:latest
    volumes:
      - ./mapi/config/add_node.sh:/add_node.sh:ro
    entrypoint: [/add_node.sh]
    restart: on-failure
    depends_on:
      - mapi

  explorer:
    container_name: explorer
    image: jwahab/woc-explorer:latest
    environment:
      PORT: "8080"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - node1

  dash:
    container_name: dash
    image: jwahab/regtest-dashboard:latest
    environment:
      DASH_PORT: 3000
      SV_HOST: node1
      SV_PORT: 18332
      SV_USER: bitcoin
      SV_PASSWORD: bitcoin
    ports:
      - "3010:3000"
    restart: unless-stopped
    depends_on:
      - node1

volumes:
  minerid:
    external: false
  headersv-data:
    external: false
  regtest-data:
  mapi-volume:
