version: "3.7"

services:
  payd:
    container_name: payd
    image: libsv/payd:0.0.3
    environment:
      DB_DSN: "file:paydb/wallet.db?cache=shared&_foreign_keys=true"
      DB_SCHEMA_PATH: "migrations"
    volumes:
      - payd-data:/paydb
    ports:
      - "8443:8443"
    networks:
      - regtest-stack
  payd-merchant:
    container_name: payd-merchant
    image: local.payd
    environment:
      DB_DSN: "file:data/merchant-wallet.db?cache=shared&_foreign_keys=true;"
      DB_SCHEMA_PATH: "migrations"
      SERVER_HOST: payd-merchant:28443
      SERVER_PORT: :28443
    volumes:
      - ./run/data:/data
    ports:
      - "28443:28443"
    networks:
      - regtest-stack

  payd-merchant:
    container_name: payd-merchant
    image: libsv/payd:0.0.3
    environment:
      DB_DSN: "file:data/merchant-wallet.db?cache=shared&_foreign_keys=true"
      DB_SCHEMA_PATH: "migrations"
      SERVER_HOST: payd-merchant:28443
      SERVER_PORT: :28443
    volumes:
      - merchant-data:/paydb
    ports:
      - "28443:28443"
    networks:
      - regtest-stack

networks:
  regtest-stack:
    external: true
    name: regtest-stack
    external: true

volumes:
  payd-data:
    external: false
  merchant-data:
    external: false